# https://starship.rs/config
add_newline = true
command_timeout = 10000
format = """
$time\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$rust\
$nodejs\
$golang\
$python\
$character"""

[aws]
disabled = true

[cmd_duration]
min_time = 15
show_milliseconds = false
disabled = false
format = "ğŸ•™ $duration($style)"

[directory]
truncate_to_repo = false
style = "bold 64"

[golang]
symbol = "î˜§ "

[git_branch]
symbol = "ï˜ "
style = "bold 63"

[git_status]
style = "bold 33"

[hostname]
ssh_only = false
style = "bold 136"

[nodejs]
symbol = "îœ˜ "

[time]
disabled = false
format = "[$time|]($style) "
style = "63"
time_format = "%H:%M"

[username]
format = "[$user]($style) at "
show_always = true
style_user = "bold 166"
